insert into rating values ('AAA','Melhor qualidade, risco de crédito extremamente baixo.','Grau de Investimento (Baixo Risco)');
insert into rating values ('AA+','Alta qualidade, muito baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('AA','Alta qualidade, muito baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('AA-','Alta qualidade, muito baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('A+',' Alta qualidade, baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('A',' Alta qualidade, baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('A-',' Alta qualidade, baixo risco.','Grau de Investimento (Baixo Risco)');
insert into rating values ('BBB+','Boa qualidade, qualidade de crédito satisfatória.','Grau de Investimento (Baixo Risco)');
insert into rating values ('BBB','Boa qualidade, qualidade de crédito satisfatória.','Grau de Investimento (Baixo Risco)');
insert into rating values ('BBB-','Boa qualidade, qualidade de crédito satisfatória.','Grau de Investimento (Baixo Risco)');
insert into rating values ('BB+',' Especulativo, maior vulnerabilidade.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('BB',' Especulativo, maior vulnerabilidade.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('BB-',' Especulativo, maior vulnerabilidade.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('B+','Risco significativo.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('B','Risco significativo.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('B-','Risco significativo.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('CCC','Alto risco de inadimplência.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('CC','Alto risco de inadimplência.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('C','Alto risco de inadimplência.','Grau Especulativo (Alto Risco/"Junk"');
insert into rating values ('D','Default (inadimplência/calote). ','Grau Especulativo (Alto Risco/"Junk"');
